name: youtube_caption_scraper
description: Parse subtitles/captions from YouTube without authorization.
version: 0.1.2
homepage: https://github.com/f-person/youtube_captions_scraper
repository: https://github.com/f-person/youtube_captions_scraper

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  html: ^0.15.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

false_secrets:
  - test/test_data.dart
