name: youtube_captions_scraper
description: Parse subtitles/captions from YouTube without authorization.
version: 1.0.0
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  html: ^0.15.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
